### ISSUE TITLE
Selecting a directory via the UIDocumentPickerViewController no longer works. 

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#107]
When a directory is selected, the title of the view controller updates correctly. But executing a command resets the current directory. Might have been broken by #104. The folder selection handling can be found in [TerminalViewController.swift](https://github.com/louisdh/terminal/blob/master/OpenTerm/Controller/TerminalViewController.swift#L354).

@holzschu Could you take a look why ios_system doesn't correctly handle selected directories anymore?

**Comment by holzschu** [comment]
> On Mar 31, 2018, at 15:14, louisdh <notifications@github.com> wrote:
> 
> When a directory is selected, the title of the view controller updates correctly. But executing a command resets the current directory. Might have been broken by #104. The folder selection handling can be found in TerminalViewController.swift.
> 
> @holzschu Could you take a look why ios_system doesn't correctly handle selected directories anymore?
> 
Oh! I think I see what I did wrong. 

Fix coming.

**Comment by holzschu** [comment]
The fix was easy, but it made me realize something else: "cd" doesn't work as expected when the user has selected a directory, because of the miniRoot system.

Scenario: 
- user selects a directory using "Open"
- user wants to go deeped in the hierarchy, types "cd downOneLevel"
- cd() checks the new directory for conformity with miniRoot. Of course it is not below the miniRoot, so the miniRoot mechanism prevents the change, and changes back to miniRoot. 
- this is not the expected behaviour.

Keeping both mechanisms is complicated. The easiest solution is to reset the miniRoot to the directory that the user has picked. 

Does it make sense?

**Comment by louisdh** [comment]
Makes sense, but isn't miniRoot global at the moment? So changing miniRoot from one tab changes it for all open tabs?

**Comment by holzschu** [comment]
You're absolutely right. 
So the consequence would be to make miniRoot local to each session as well.

**Comment by holzschu** [comment]
In the end, it was more complicated. 
miniRoot remains global
Each session can have a localMiniRoot, corresponding to the path they are authorized to access).
Changing into a directory is permitted if:
- it exists,
- the system allows reading it,
- the system allows changing into it,
- it is below either the miniRoot or the localMiniRoot (if they exist).

"cd -" does the right thing, and two different tabs can have different local miniRoots.
