### ISSUE TITLE
ANSI colors not enabled anymore?

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#109]
@holzschu I remember that `ls` used to output a different color for directories. In the current version those colors have disappeared. Perhaps this got disabled while moving to ios_system 2.0?

**Comment by holzschu** [comment]
They should not have disappeared, and they're still there for me.

I see three possible causes: 
a) environment variables that are not set. 
b) ls thinks it is sending its data to another program, instead of a tty.
c) color management disappeared. 

- Symptoms of b: ls outputs a single column, instead of its usual multi-column output
- Testing for c: try "curl wttr.in", does it have color?
- Testing for a: type "env | grep COLOR"

**Comment by louisdh** [comment]
a) env is set
b) ls outputs a single column
c) `curl wttr.in` shows colors

So what's wrong with my `ls` config?

**Comment by holzschu** [comment]
With these symptoms, it's likely that the "isatty(STDOUT_FILENO)" test fails (line 429 of ls.c).
This test checks whether "fileno(thread_stdout) == fileno(currentSession.stdout)". 

It's likely that one of these hasn't been set. 
currentSession.stdout is set, before the first command is started, by "ios_setStreams" (line 93 of commandExecutor.swift). 
thread_stdout is a thread local variable. It is set to null immediately before the call to "ios_system" (line 194 of commandExecutor.swift), and thus will be initialized in ios_system to currentSession.stdout (line 744 of ios_system.m).

What might have happened is that one of these lines disappeared in a git commit. I'll pull a new branch and see if I can see differences.
