### ISSUE TITLE
Not available in Japan App Store 

### ISSUE THREAD

**Issue by zshbleaker** [louisdh/terminal#166]
Thanks for developing an awesome terminal emulator for sysadmins on the go and publishing OpenTerm on App Store. However its unavailable in Japan, where iOS takes for more than 80% market share of mobile devices. 

Could you extend OpenTerm to more contries? It would be pretty awesome for we living in Far East.

**Comment by kkebo** [comment]
OpenTerm has been removed from the App Store in not only Japan but also the other countries since @louisdh joined Apple.
https://twitter.com/louisdhauwe/status/1052003267612299266?s=21

Instead, I recommend [Blink Shell](
https://itunes.apple.com/us/app/blink-shell-mosh-ssh/id1156707581?mt=8) or [LibTerm](
https://itunes.apple.com/us/app/libterm/id1380911705?mt=8). Both of them are using [ios_system](
https://github.com/holzschu/ios_system) as OpenTerm is.

**Comment by zshbleaker** [comment]
> OpenTerm has been removed from the App Store in not only Japan but also the other countries since @louisdh joined Apple.
> https://twitter.com/louisdhauwe/status/1052003267612299266?s=21
> 
> Instead, I recommend [Blink Shell](
> https://itunes.apple.com/us/app/blink-shell-mosh-ssh/id1156707581?mt=8) or [LibTerm](
> https://itunes.apple.com/us/app/libterm/id1380911705?mt=8). Both of them are using [ios_system](
> https://github.com/holzschu/ios_system) as OpenTerm is.

Oh it’s pretty sad. Thanks for reminding. I’ll look for an alternative.
