### ISSUE TITLE
grep redirection from < file not working

### ISSUE THREAD

**Issue by palmin** [louisdh/terminal#36]
While working on #26 I am having problems getting input redirection to work.

It can be replicated by entering

    : echo test > test
    : grep e test
    test
    
    : grep e < test
    : 
where the problem is that the last `grep` does not output anything, since it should be working on stdin.

@holzschu I was able to fix the problem for `x-callback-url` by using `fileno(stdin)` instead of STDIN_FILENO as you suggest in the docs, but it seems `grep` does not do this. Let me know if you would like a PR for this.

**Comment by holzschu** [comment]
I cannot reproduce the issue here:
![c7d9959b-aca3-47f5-8029-927d7f90cee2](https://user-images.githubusercontent.com/8070736/35329958-f5879830-0101-11e8-9465-c164878bdb1e.jpeg)

Could it be an issue with versions? There should be no "_fileno" or "_FILENO" inside grep.c. I'm going to check whether I committed everything.

**Comment by palmin** [comment]
It very well could be something with versions. 

I could replicate with both the App Store version and a fresh clone of this repo just letting CocoaPods handle `ios_system` but for me CocoaPods is something of a black box. 

I do see commits from January 20th by you in `ios_system.m` making it seem pretty recent.

**Comment by palmin** [comment]
Let us see if anybody else sees this issue and take it from there.
