### ISSUE TITLE
Adding ffmpeg

### ISSUE THREAD

**Issue by louisdh** [louisdh/terminal#59]

**Comment by palmin** [comment]
I feel a little like a doomsday prophet continuously warning about the GPL, but I really think some free software advocates might think it unfair that a shell running on a non-free platform have access to GPL software and would file a claim against the app.

Some parts of ffmpeg are GPL and some are LGPL:
 https://www.ffmpeg.org/legal.html
and while regular GPL it not compatible with the App Store terms, when using just the LGPL components it is important that this is put in a shared framework and not statically linked with the main app.

**Comment by IMcD23** [comment]
@palmin It's unfortunate that the licenses are incompatible with the App Store, but thanks for pointing these issues out.

**Comment by palmin** [comment]
@IMcD23 The Working Copy users have been begging me to bundle command line Git for years, making this something I have spent more time worrying about than I would have liked.

**Comment by louisdh** [comment]
Ok, thanks for your input @palmin. I suppose it's fair to close this issue?

**Comment by IMcD23** [comment]
Now that ios_system links commands dynamically, and since all of the code interfacing with ffmpeg would be open-source...

IANAL, but after reading [this thread](https://trac.ffmpeg.org/ticket/1229), I think we'd be fine to include this as a command.

**Comment by palmin** [comment]
I think it depends on whether it is only the LGPL or GPL parts that are included. I'm not sure about the situation for LGPL but for GPL it is not sufficient that the code is open-source. 

> Each time you redistribute the Program (or any work based on the Program), the recipient automatically receives a license from the original licensor to copy, distribute or modify the Program subject to these terms and conditions. You may not impose any further restrictions on the recipients' exercise of the rights granted herein.

https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement

Since distribution on the iOS App Store has all sorts of restrictions, there is (in the eyes of FSF) no legal way to include GPL code in the App Store.

The more prominent the project becomes, the higher the risk that somebody will complain about licensing, as a open-source advocate might see it as unfair that a non-open software platform can benefit from free (GPL'ed) code.
